### PR TITLE
Update provider_power_node.cc

### PR DESCRIPTION
**Pull request by supertoto29**
**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Remove the spam with proc_fault. There should be a better implementation but for tmr this is going to work. The changes can be made at the same time as the integration on AUV7.

This is to remove the spam on the rosout for the test of the 2022-06-26.

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by 0x72D0 — CHANGES_REQUESTED** [review]
the message that was spamming wasn't unknown SLAVE but unknown CMD

**Comment by supertoto29** [comment]
Gonna have to change it tmr then

**Review by 0x72D0 — APPROVED** [review]
LGTM!

**Review by 0x72D0 — APPROVED** [review]
LGTM!

**Comment by supertoto29** [comment]
I will merge develop into master to create a backup before merging this pull request

**Pull request merged**
